typography_spectrum: 0.5161461851093918
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.20211292896419764
  lightness: 0.05299368337728083
  saturation: 0.25825219159014523
  rhythmicContrast: 0.0772020595613867
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4704030817374587
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/62c228c6-d401-4239-902a-7948b2a3583c.psd
name: LitoPad
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: www.litopad.com
    type: external
favicon: null
title: LITO PAD
description: 'Bass player, Dj / Producer'
purpose: []
