layout_spectrum: 0.2219941474031657
typography_spectrum: 0.3611543965525925
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.5979752182029188
  lightness: 0.3438664423301816
  saturation: 0.9028172632679343
  rhythmicContrast: 0.8810040806420147
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ead5d509-e497-4c98-a11f-e1a3f2ce1bd1.jpg
name: LitoPad
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: LITO PAD
description: 'Bass player, Dj / Producer'
purpose: []
