layout_spectrum: 0.2219941474031657
typography_spectrum: 0.7251637754961848
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.8156011365354061
  lightness: 0.42304957238957286
  saturation: 0.539452661992982
  rhythmicContrast: 0.29115566122345626
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ead5d509-e497-4c98-a11f-e1a3f2ce1bd1.jpg
name: LitoPad
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: LITO PAD
description: 'Bass player, Dj / Producer'
purpose: []
